<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BudgetGLAccountsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $accounts = [
            ['CurrencyID' => 1, 'GLName' => 'GL-100001', 'Description' => 'OFFICE EQUIPMENT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-100002', 'Description' => 'COMPUTER SOFTWARE', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-100003', 'Description' => 'FURNITURE AND FITTINGS', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-100004', 'Description' => 'MOTOR VEHICLES', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-100005', 'Description' => 'LAND AND BUILDINGS', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-100006', 'Description' => 'LEASEHOLD IMPROVEMENTS', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-100007', 'Description' => 'INTANGIBLES', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-100044', 'Description' => 'FINANCIAL ASSETS', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-100050', 'Description' => 'PLACEMENTS', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-100101', 'Description' => 'ACC. DEPN. OFFICE EQUIPMENT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-100102', 'Description' => 'ACC. DEPN. SOFTWARE', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-100103', 'Description' => 'ACC.DEPN. FURNITURE AND FITTINGS', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-100104', 'Description' => 'ACC. DEPN. MOTOR VEHICLES', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-100105', 'Description' => 'ACC. DEPN. LAND AND BUILDINGS', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-100106', 'Description' => 'ACC. DEPN. LEASEHOLD IMPROVEMENTS', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-100107', 'Description' => 'ACC.DEPN. INTANGIBLES', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-100204', 'Description' => 'INTERBRANCH DISBURSEMENTS', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-100219', 'Description' => 'INTERBRANCH SUSPENSE ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-100322', 'Description' => 'LOAN DISBURSEMENT SUSPENSE', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-100401', 'Description' => 'Other Assets Pre Opening Exp', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-100410', 'Description' => 'PREPAYMENTS', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-100411', 'Description' => 'QSR INTERCOMPANY BALANCE ZWL', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-101001', 'Description' => 'MICRO LOAN CONTROL ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-101002', 'Description' => 'SALARY BASED LOAN CONTROL ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-101003', 'Description' => 'SME LOAN CONTROL ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-101004', 'Description' => 'CORP3 CONTROL ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-101005', 'Description' => 'CORP6 CONTROL ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-101006', 'Description' => 'ZWL LOAN FACILITIES WITH BULLET PAYMENTS CONTROL ACC', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-101010', 'Description' => 'ML001 CONTROL ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-101011', 'Description' => 'SSB LOAN CONTROL ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-102001', 'Description' => 'MICRO LOAN INTEREST RECEIVABLE', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-102002', 'Description' => 'SALARY BASED LOAN INTEREST RECEIVABLE', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-102003', 'Description' => 'SME LOAN INTEREST RECEIVABLE', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-102004', 'Description' => 'CORP3 INTEREST RECEIVABLE', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-102005', 'Description' => 'CORP6 INTEREST RECEIVABLE', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-102006', 'Description' => 'ZWL LOAN FACILITIES WITH BULLET PAYMENTS INTEREST RECEIVABLE', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-102011', 'Description' => 'SSB INTEREST RECEIVABLE', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-102020', 'Description' => 'ML001 INTEREST RECEIVABLE ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-102101', 'Description' => 'TB02 ADVANCE INTEREST RECEIVABLE', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-102110', 'Description' => 'MICRO LOAN SUSPENDED INTEREST RECEIVABLE', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-102111', 'Description' => 'SALARY BASED LOAN SUSPENDED INTEREST RECEIVABLE', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-102112', 'Description' => 'SME LOAN SUSPENDED INTEREST RECEIVABLE', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-102113', 'Description' => 'SSB SUSPENDED INTEREST', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-102114', 'Description' => 'CORP3 SUSPENDED INTEREST RECEIVABLE', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-102115', 'Description' => 'CORP6 SUSPENDED INTEREST RECEIVABLE', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-102116', 'Description' => 'ZWL LOAN FACILITIES WITH BULLET PAYMENTS SUSPENDED INTEREST RECEIVABLE', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-102201', 'Description' => 'REPO INTEREST RECEIVABLE ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-102202', 'Description' => 'REVPO INTEREST RECEIVABLE ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-102203', 'Description' => 'CP01 DISCOUNT ON PURCHASE', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-102204', 'Description' => 'CP01 INTEREST RECEIVABLE ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-102205', 'Description' => 'TB01 INTEREST RECEIVABLE ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-102206', 'Description' => 'TB01 DISCOUNT ON PURCHASE', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-104009', 'Description' => 'MONEY MARKET LENDING', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-104071', 'Description' => 'BUREAUX DE CHANGE SETTLEMENT ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-104101', 'Description' => 'INTER BRANCH ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-104103', 'Description' => 'REVPO CONTROL ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-104104', 'Description' => 'TB01 CONTROL ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-104201', 'Description' => 'TB02 CONTROL ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-104202', 'Description' => 'REPO CONTROL ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-104203', 'Description' => 'CP01 CONTROL ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-105001', 'Description' => 'PETTY CASH', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-105002', 'Description' => 'TELLER VAULT ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-105003', 'Description' => 'CBZ BANK ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-105004', 'Description' => 'ECOBANK', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-105005', 'Description' => 'TELLER 1', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-105006', 'Description' => 'ECOBANK RTGS', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-105007', 'Description' => 'ECOBANK SALARY ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-105008', 'Description' => 'RBZ NDORO MICROFINANCE RTGS', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-105009', 'Description' => 'RBZ NCD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-105010', 'Description' => 'INNBUCKS HEADOFFICE CASH', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-105011', 'Description' => 'ZIPIT SEND', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-105014', 'Description' => 'TELLER 2', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-105024', 'Description' => 'TELLER 3', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-105025', 'Description' => 'TELLER 4', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-105026', 'Description' => 'TELLER 5', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-105027', 'Description' => 'TELLER 6', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-105028', 'Description' => 'TELLER 7 ZWL', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-105048', 'Description' => 'CASH IN TRANSIT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-105060', 'Description' => 'FOREX TRADING ZWL', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-105101', 'Description' => 'SETTLEMENT ACCOUNT - ZIG', 'GTType' => 'ASSET'],
            ['CurrencyID' => 2, 'GLName' => 'GL-105102', 'Description' => 'SETTLEMENT ACCOUNT ZAR', 'GTType' => 'ASSET'],
            ['CurrencyID' => 3, 'GLName' => 'GL-105103', 'Description' => 'SETTLEMENT ACCOUNT - GBP', 'GTType' => 'ASSET'],
            ['CurrencyID' => 4, 'GLName' => 'GL-105104', 'Description' => 'SETTLEMENT ACCOUNT - BWP', 'GTType' => 'ASSET'],
            ['CurrencyID' => 5, 'GLName' => 'GL-105105', 'Description' => 'SETTLEMENT ACCOUNT - YEN', 'GTType' => 'ASSET'],
            ['CurrencyID' => 6, 'GLName' => 'GL-105106', 'Description' => 'SETTLEMENT ACCOUNT - AUD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 7, 'GLName' => 'GL-105107', 'Description' => 'SETTLEMENT ACCOUNT - CAD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 8, 'GLName' => 'GL-105108', 'Description' => 'SETTLEMENT ACCOUNT - INR', 'GTType' => 'ASSET'],
            ['CurrencyID' => 9, 'GLName' => 'GL-105109', 'Description' => 'SETTLEMENT ACCOUNT - EUR', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-105110', 'Description' => 'SETTLEMENT ACCOUNT - USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-105202', 'Description' => 'VAULT ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-105203', 'Description' => 'VAULT ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-105301', 'Description' => 'RTGS Suspense Account', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-105302', 'Description' => 'TELLER 1', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-105402', 'Description' => 'VAULT ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-106001', 'Description' => 'INNBUCKS STATUTORY RESERVE ZWL', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-110001', 'Description' => 'OFFICE EQUIPMENT USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-110002', 'Description' => 'COMPUTER SOFTWARE USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-110003', 'Description' => 'FURNITURE AND FITTINGS USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-110004', 'Description' => 'MOTOR VEHICLES USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-110005', 'Description' => 'INTANGIBLE ASSETS', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-110006', 'Description' => 'LEASED ASSETS OFFICE PREMISES', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-110007', 'Description' => 'COMPUTER EQUIPMENT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-110044', 'Description' => 'FINANCIAL ASSETS USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-110050', 'Description' => 'PLACEMENTS USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 2, 'GLName' => 'GL-110051', 'Description' => 'PLACEMENTS ZAR', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-110101', 'Description' => 'ACC. DEPN. OFFICE EQUIPMENT USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-110103', 'Description' => 'ACC.DEPN. FURNITURE AND FITTINGS USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-110104', 'Description' => 'ACC. DEPN. MOTOR VEHICLES USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-110105', 'Description' => 'ACC. DEPN. LEASED ASSETS', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-110106', 'Description' => 'ACC. DEPN. COMPUTER SOFTWARE', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-110107', 'Description' => 'ACC. DEPN. COMPUTER EQUIPEMENT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-110401', 'Description' => 'OTHER ASSETS PRE OPENING EXP USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-110410', 'Description' => 'PREPAYMENTS AIRTIME', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-110411', 'Description' => 'QSR INTERCOMPANY BALANCE USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-110412', 'Description' => 'CASH 24 INTERCOMPANY BALANCE USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-110413', 'Description' => 'PROVIDENCE HUMAN CAPITAL INTERCOMPANY BALANCE USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-110414', 'Description' => 'STAFF DEBTORS CONTROL INTERCOMPANY BALANCE USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-110415', 'Description' => 'PREPAYMENTS WALLET', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-110416', 'Description' => 'PREPYAMENT RENT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-110417', 'Description' => 'PREPAYMENT COMMISSION', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-110418', 'Description' => 'PREPAYMENT GENERAL', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-110419', 'Description' => 'USD AUCTION DISCOUNTING FACILITIES', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-110420', 'Description' => 'PREPAYMENT ZESA', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-110421', 'Description' => 'RBZ AUCTION FUNDS RECEIVABLE', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-110422', 'Description' => 'AIRTIME PURCHSE PREPAYMENT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-110423', 'Description' => 'DEBIT CARDS IVENTORY', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-110424', 'Description' => 'RECEIVABLES', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-111001', 'Description' => 'MICRO LOAN CONTROL ACCOUNT USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-111002', 'Description' => 'SALARY BASED LOAN CONTROL ACCOUNT USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-111003', 'Description' => 'SME LOAN CONTROL ACCOUNT USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-111004', 'Description' => 'CORP CONTROL ACCOUNT USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-111005', 'Description' => 'STAFF LOAN CONTROL ACCOUNT USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-111006', 'Description' => 'PROVSBL CONTROL ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-111007', 'Description' => 'FORMER STAFF LOAN CONTROL ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-111008', 'Description' => 'WEEKLY SBL CONTROL ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-111009', 'Description' => 'WHOLESALE CONTROL ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-111010', 'Description' => 'ML002 CONTROL ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-111011', 'Description' => 'SSB LOAN CONTROL ACCOUNT USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-111012', 'Description' => 'SBLMID CONTROL ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-111013', 'Description' => 'CAR LOAN CONTROL ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-111014', 'Description' => 'DEBT FACTORING CONTROL STURCTURED FINANCE', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-111015', 'Description' => 'STAFF CAR LOAN CONTROL ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 2, 'GLName' => 'GL-111016', 'Description' => 'ML CONTROL ACCOUNT ZAR', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-111017', 'Description' => 'USD LOAN FACILITIES WITH BULLET PAYMENTS CONTROL ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-112001', 'Description' => 'MICRO LOAN INTEREST RECEIVABLE USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-112002', 'Description' => 'SALARY BASED LOAN INTEREST RECEIVABLE USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-112003', 'Description' => 'SME LOAN INTEREST RECEIVABLE USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-112004', 'Description' => 'CORP INTEREST RECEIVABLE USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-112005', 'Description' => 'STAFF LOAN INTEREST RECEIVABLE USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-112006', 'Description' => 'PROVSBL INTEREST RECEIVEABLE', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-112007', 'Description' => 'FORMER STAFF LOAN INTEREST RECEIVEABLE', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-112008', 'Description' => 'WEEKLY SBL INTEREST RECEIVEABLE', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-112009', 'Description' => 'WHOLESALE INTEREST RECEIVEABLE', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-112011', 'Description' => 'SSB INTEREST RECEIVABLE USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-112012', 'Description' => 'SBLMID INTEREST RECEIVABLE', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-112013', 'Description' => 'CAR LOAN INTEREST RECEIVABLE', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-112014', 'Description' => 'DEBT FACTORG INTEREST RECEIVABLE', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-112015', 'Description' => 'STAFF CAR LOAN INST RECEIVABLE', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-112016', 'Description' => 'USD LOAN FACILITIES WITH BULLET PAYMENTS SUSPENDED INTEREST RECEIVABLE', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-112017', 'Description' => 'USD LOAN FACILITIES WITH BULLET PAYMENTS INTEREST RECEIVABLE', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-112020', 'Description' => 'ML002 INTEREST RECEIVABLE ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 2, 'GLName' => 'GL-112021', 'Description' => 'ML INTEREST RECEIVABLE ACCOUNT ZAR', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-112110', 'Description' => 'MICRO LOAN SUSPENDED INTEREST RECEIVABLE USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-112111', 'Description' => 'SALARY BASED LOAN SUSPENDED INTEREST RECEIVABLE USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-112112', 'Description' => 'SME LOAN SUSPENDED INTEREST RECEIVABLE USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-112113', 'Description' => 'SSB SUSPENDED INTEREST USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-112114', 'Description' => 'CORP SUSPENDED INTEREST RECEIVABLE USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-112115', 'Description' => 'STAFF LOAN SUSPENDED INTEREST RECEIVABLE USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-112116', 'Description' => 'PROVSBL SUSPENDED INTEREST RECEIVEABLE', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-112117', 'Description' => 'FORMER STAFF SUSPENDED INTEREST RECEIVEABLE', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-112118', 'Description' => 'WEEKLY SBL SUSPENDED INTEREST RECEIVEABLE', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-112119', 'Description' => 'WHOLESALE SUSPENDED INTEREST RECEIVEABLE', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-112122', 'Description' => 'SBLMID SUSPENDED INTEREST RECEIVABLE', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-112123', 'Description' => 'CAR SUSPENDED INTEREST RECEIVABLE USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-112124', 'Description' => 'DEBT FACTORING SUSPENDED INTEREST RECEIVABLE USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-112125', 'Description' => 'STAFF CAR LOAN SUSPENDED INTEREST RECEIVABLE', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-113001', 'Description' => 'TRADE DEBTORS USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-114001', 'Description' => 'NOSTRO FCA EXPORTS 25 LIQ', 'GTType' => 'ASSET'],
            ['CurrencyID' => 2, 'GLName' => 'GL-114002', 'Description' => 'NOSTRO FCA EXPORTS 25 LIQ', 'GTType' => 'ASSET'],
            ['CurrencyID' => 9, 'GLName' => 'GL-114003', 'Description' => 'NOSTRO FCA EXPORTS 25 LIQ', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-114009', 'Description' => 'MONEY MARKET LENDING', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-114011', 'Description' => 'NOSTRO FCA DOMESTIC 15 LIQ', 'GTType' => 'ASSET'],
            ['CurrencyID' => 2, 'GLName' => 'GL-114012', 'Description' => 'NOSTRO FCA DOMESTIC 15 LIQ', 'GTType' => 'ASSET'],
            ['CurrencyID' => 9, 'GLName' => 'GL-114013', 'Description' => 'NOSTRO FCA DOMESTIC 15 LIQ', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-114015', 'Description' => 'LIQUIDATIONS SUSPENSE ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-114016', 'Description' => 'RTGS SUSPENSE TREASURY ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-114021', 'Description' => 'NOSTRO FCA INVESTMENTS 0 LIQ', 'GTType' => 'ASSET'],
            ['CurrencyID' => 2, 'GLName' => 'GL-114022', 'Description' => 'NOSTRO FCA INVESTMENTS 0 LIQ', 'GTType' => 'ASSET'],
            ['CurrencyID' => 9, 'GLName' => 'GL-114023', 'Description' => 'NOSTRO FCA INVESTMENTS 0 LIQ', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-114031', 'Description' => 'NON RESIDENT NOSTRO FCA O LIQ', 'GTType' => 'ASSET'],
            ['CurrencyID' => 2, 'GLName' => 'GL-114032', 'Description' => 'NON RESIDENT NOSTRO FCA O LIQ', 'GTType' => 'ASSET'],
            ['CurrencyID' => 9, 'GLName' => 'GL-114033', 'Description' => 'NON RESIDENT NOSTRO FCA O LIQ', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-114041', 'Description' => 'NGO EMBASSY NOSTRO FCA 0 LIQ', 'GTType' => 'ASSET'],
            ['CurrencyID' => 2, 'GLName' => 'GL-114042', 'Description' => 'NGO EMBASSY NRO FCA 0 LIQ', 'GTType' => 'ASSET'],
            ['CurrencyID' => 9, 'GLName' => 'GL-114043', 'Description' => 'NGO EMBASSY NRO FCA 0 LIQ', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-114051', 'Description' => 'BANK NOSTRO FCA 0 LIQ', 'GTType' => 'ASSET'],
            ['CurrencyID' => 2, 'GLName' => 'GL-114052', 'Description' => 'BANK NOSTRO FCA 0 LIQ', 'GTType' => 'ASSET'],
            ['CurrencyID' => 9, 'GLName' => 'GL-114053', 'Description' => 'BANK NOSTRO FCA 0 LIQ', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-114061', 'Description' => 'TRANSITORY NOSTRO FCA 0 LIQ', 'GTType' => 'ASSET'],
            ['CurrencyID' => 2, 'GLName' => 'GL-114062', 'Description' => 'TRANSITORY NOSTRO FCA 0 LIQ', 'GTType' => 'ASSET'],
            ['CurrencyID' => 9, 'GLName' => 'GL-114063', 'Description' => 'TRANSITORY NOSTRO FCA 0 LIQ', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-114071', 'Description' => 'BUREAUX DE CHANGE TRADING ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-114072', 'Description' => 'ACCESS BANK USD NOSTRO GL', 'GTType' => 'ASSET'],
            ['CurrencyID' => 2, 'GLName' => 'GL-114073', 'Description' => 'ACCESS BANK ZAR NOSTRO GL', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-114074', 'Description' => 'ACCESS BANK BW USD NOSTRO', 'GTType' => 'ASSET'],
            ['CurrencyID' => 2, 'GLName' => 'GL-114075', 'Description' => 'ACCESS BANK BW ZAR NOSTRO', 'GTType' => 'ASSET'],
            ['CurrencyID' => 3, 'GLName' => 'GL-114076', 'Description' => 'ACCESS BANK BW GBP NOSTRO', 'GTType' => 'ASSET'],
            ['CurrencyID' => 9, 'GLName' => 'GL-114077', 'Description' => 'ACCESS BANK BW EUR NOSTRO', 'GTType' => 'ASSET'],
            ['CurrencyID' => 4, 'GLName' => 'GL-114078', 'Description' => 'ACCESS BANK BW BWP', 'GTType' => 'ASSET'],
            ['CurrencyID' => 4, 'GLName' => 'GL-114079', 'Description' => 'ACCESS BANK BW BWP NOSTRO CURRENT ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-114081', 'Description' => 'BIDVEST USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 2, 'GLName' => 'GL-114082', 'Description' => 'BIDVEST ZAR', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-115001', 'Description' => 'INNBUCK HEAD OFFICE CASH USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-115002', 'Description' => 'TELLER VAULT ACCOUNT USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-115003', 'Description' => 'CBZ USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-115004', 'Description' => 'PETTY CASH USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-115005', 'Description' => 'TELLER 1 USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-115006', 'Description' => 'ECOBANK USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-115007', 'Description' => 'ZIMSWITCH COLLATERAL ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-115008', 'Description' => 'RBZ NDORO FCA DOMESTIC SETTLEMENT USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 2, 'GLName' => 'GL-115009', 'Description' => 'CBZ ZAR', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-115010', 'Description' => 'INNBUCKS HEADOFFICE PETTY CASH USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-115011', 'Description' => 'INNBUCKS CABS ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-115012', 'Description' => 'ZIG VAULT ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-115013', 'Description' => 'TELLER ZIG VAULT ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-115014', 'Description' => 'TELLER 2 USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-115015', 'Description' => 'ZIPIT SEND USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-115016', 'Description' => 'CBZ VISA CARD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-115017', 'Description' => 'InnBucks CSN Remittance Account - Cash', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-115018', 'Description' => 'InnBucks CSN Remittance Cabin Float Account at Gains', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-115020', 'Description' => 'CASH COVER SECURITY USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-115024', 'Description' => 'TELLER 3 USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-115025', 'Description' => 'TELLER 4 USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-115026', 'Description' => 'TELLER 5 USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-115027', 'Description' => 'TELLER 6 USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-115028', 'Description' => 'TELLER 7 USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-115038', 'Description' => 'BRANCH SUSPENSE ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-115048', 'Description' => 'CASH IN TRANSIT USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-115049', 'Description' => 'EXCESS USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-115050', 'Description' => 'TELLER DIFFERENCE', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-115051', 'Description' => 'CASH TWENTY FOUR SUSPENSE CASH IN TRANSIT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-115060', 'Description' => 'FOREX TRADING USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 2, 'GLName' => 'GL-115061', 'Description' => 'FOREX TRADING ZAR', 'GTType' => 'ASSET'],
            ['CurrencyID' => 4, 'GLName' => 'GL-115062', 'Description' => 'BWP FX TRADING ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 9, 'GLName' => 'GL-115063', 'Description' => 'EUR FX TRADING ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 3, 'GLName' => 'GL-115064', 'Description' => 'GBP FX TRADING ACCOUNT', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-115101', 'Description' => 'SETTLEMENT ACCOUNT - USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 2, 'GLName' => 'GL-115102', 'Description' => 'SETTLEMENT ACCOUNT ZAR', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-115111', 'Description' => 'SETTLEMENT ACCOUNT ZIG', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-115202', 'Description' => 'VAULT ACCOUNT USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-115203', 'Description' => 'VAULT ACCOUNT USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-115204', 'Description' => 'INTERBRANCH ACCOUNT USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 10, 'GLName' => 'GL-116001', 'Description' => 'INNBUCKS STATUTORY RESERVE USD', 'GTType' => 'ASSET'],
            ['CurrencyID' => 1, 'GLName' => 'GL-200000', 'Description' => 'ORDINARY SHARE CAPITAL', 'GTType' => null],
            ['CurrencyID' => 1, 'GLName' => 'GL-200085', 'Description' => 'TRADE CREDITORS', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-200095', 'Description' => 'FINANCIAL LIABILITIES', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-201000', 'Description' => 'SHARE PREMIUM', 'GTType' => null],
            ['CurrencyID' => 1, 'GLName' => 'GL-203100', 'Description' => 'CURRENT YEAR RETAINED EARNING', 'GTType' => null],
            ['CurrencyID' => 10, 'GLName' => 'GL-220000', 'Description' => 'ORDINARY SHARE CAPITAL USD', 'GTType' => null],
            ['CurrencyID' => 10, 'GLName' => 'GL-220001', 'Description' => 'SHARE PREMIUM USD', 'GTType' => null],
            ['CurrencyID' => 10, 'GLName' => 'GL-221001', 'Description' => 'RETAINED EARNINGS INNBUCKS USD', 'GTType' => null],
            ['CurrencyID' => 10, 'GLName' => 'GL-223100', 'Description' => 'RETAINED EARNINGS USD', 'GTType' => null],
            ['CurrencyID' => 1, 'GLName' => 'GL-300095', 'Description' => 'FINANCIAL LIABILITIES', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-300096', 'Description' => 'ZimSwitch Suspence Account ZWL', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-301001', 'Description' => 'RELATED PARTY LOANS', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-301002', 'Description' => 'LONG TERM LOANS', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-301003', 'Description' => 'RBZ LOAN', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-303001', 'Description' => 'UNCLAIMED DEPOSITS- POS ZIPIT', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-303003', 'Description' => 'UNCLAIMED DEPOSITS- ECOCASH', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-303004', 'Description' => 'UNCLAIMED DEPOSITS- ONE WALLET', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-303007', 'Description' => 'MOMBE FIXED DEPOSIT CONTROL', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-303009', 'Description' => 'MONEY MARKET BORROWING', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-303010', 'Description' => 'LOAN SETTLEMENT ACCOUNT', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-303011', 'Description' => 'MB01 CONTROL ACCOUNT', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-303012', 'Description' => 'MOMBE STAFF ACCOUNT', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-303013', 'Description' => 'Mombe Staff Control Account', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-303101', 'Description' => 'ACCOUNT CLOSED SUSPENSE', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-303102', 'Description' => 'CREDIT SUSPENSE ACCOUNT ZWL', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-303103', 'Description' => 'FINANCE EFT ZWL', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-305001', 'Description' => 'MB01 INTEREST PAYABLE ACCOUNT', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-305003', 'Description' => 'MOMBE FDD INTEREST PAYABLE', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-306001', 'Description' => 'MICRO LOAN GENERAL LOAN LOSS PROVISION', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-306002', 'Description' => 'MICRO LOAN SPECIFIC LOAN LOSS PROVISION', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-306003', 'Description' => 'SME LOAN GENERAL LOAN LOSS PROVISION', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-306004', 'Description' => 'SME LOAN SPECIFIC LOAN LOSS PROVISION', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-306005', 'Description' => 'CORP3 GENERAL LOAN LOSS PROVISION', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-306006', 'Description' => 'CORP6 GENERAL LOAN LOSS PROVISION', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-306007', 'Description' => 'SALARY BASED LOAN GENERAL LOAN LOSS PROVISION', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-306008', 'Description' => 'SALARY BASED LOAN SPECIFIC LOAN LOSS PROVISION', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-306009', 'Description' => 'SSB SPECIFIC LOAN LOSS PROVISION', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-306010', 'Description' => 'SSB GENERAL LOAN LOSS PROVISION', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-306012', 'Description' => 'CORP6 SPECIFIC LOAN LOSS PROVISION', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-306013', 'Description' => 'CORP3 GENERAL LOAN LOSS PROVISION', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-306014', 'Description' => 'ZWL LOAN FACILITIES WITH BULLET PAYMENTS GENERAL LOAN LOSS PROVISION', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-306015', 'Description' => 'ZWL LOAN FACILITIES WITH BULLET PAYMENTS SPECIFIC LOAN LOSS PROVISION', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-307001', 'Description' => 'Intermediated Money Transfer Tax', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-307004', 'Description' => 'TRADE CREDITORS', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-307012', 'Description' => 'RBZ PENALTIES SUSPENSE', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-307101', 'Description' => 'BUSINESS SAVINGS CONTROL ACCOUNT', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-307103', 'Description' => 'MOMBE PREMIER CONTROL ACCOUNT', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-307104', 'Description' => 'MOMBE BUSINESS CONTROL ACCOUNT', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-307105', 'Description' => 'Mombe Access Control Account', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-307106', 'Description' => 'MOMBE ACCESS PLUS CONTROL ACCOUNT', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-307111', 'Description' => 'MFD Fixed Deposit Control Account', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-307112', 'Description' => 'LNSP CONTROL ACCOUNT', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-307201', 'Description' => 'BUSINESS SAVINGS INTEREST PAYABLE', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-307203', 'Description' => 'REVPO INTEREST PAYABLE ACCOUNT', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-307211', 'Description' => 'MFD Interest Payable Account', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-307301', 'Description' => 'WITHHOLDING TAX', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-307411', 'Description' => 'INTERNAL TRANSACTION ACCOUNT ZWL', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-308001', 'Description' => 'ZIG CONVERSION SUSPENSE ACCOUNT', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-308002', 'Description' => 'ZIG CONVERSION SUSPENSE ACCOUNT', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-308101', 'Description' => 'INDIVIDUAL SAVINGS CONTROL ACCOUNT', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-308201', 'Description' => 'INDIVIDUAL SAVINGS INTEREST PAYABLE', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-309001', 'Description' => 'ZIG CONVERSION SUSPENSE FINANCE ACCOUNT', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 1, 'GLName' => 'GL-309002', 'Description' => 'ZIG CONVERSION SUSPENSE FINANCE ACCOUNT', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 10, 'GLName' => 'GL-315001', 'Description' => 'MB02 INTEREST PAYABLE ACCOUNT USD', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 10, 'GLName' => 'GL-330006', 'Description' => 'LEASE LIABILITY', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 10, 'GLName' => 'GL-330095', 'Description' => 'FINANCIAL LIABILITIES USD', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 10, 'GLName' => 'GL-330096', 'Description' => 'ZimSwitch Suspence Account USD', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 10, 'GLName' => 'GL-331001', 'Description' => 'RELATED PARTY LOANS USD', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 10, 'GLName' => 'GL-332001', 'Description' => 'NOSTRO FCA OFFSHORE LOANS 0 LIQ', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 2, 'GLName' => 'GL-332002', 'Description' => 'NOSTRO FCA OFFSHORE LOANS 0 LIQ', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 9, 'GLName' => 'GL-332003', 'Description' => 'NOSTRO FCA OFFSHORE LOANS 0 LIQ', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 10, 'GLName' => 'GL-332004', 'Description' => 'NOSTRO FCA OFFSHORE LOANS', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 10, 'GLName' => 'GL-333009', 'Description' => 'MONEY MARKET BORROWING', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 10, 'GLName' => 'GL-333011', 'Description' => 'MB02 CONTROL ACCOUNT', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 2, 'GLName' => 'GL-333012', 'Description' => 'MB CONTROL ACCOUNT ZAR', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 10, 'GLName' => 'GL-333013', 'Description' => 'STAFF CONTROL ACCOUNT USD', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 10, 'GLName' => 'GL-333101', 'Description' => 'CREDIT SUSPENSE ACCOUNT USD', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 10, 'GLName' => 'GL-333102', 'Description' => 'OPERATIONS SUSPENSE USD', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 10, 'GLName' => 'GL-333103', 'Description' => 'FINANCE EFT USD', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 10, 'GLName' => 'GL-333104', 'Description' => 'EDGARS INCIDENT SUSPENSE ACCOUNT', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 10, 'GLName' => 'GL-333201', 'Description' => 'INVALID ACCOUNT USD', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 10, 'GLName' => 'GL-333301', 'Description' => 'CONTRA ACCOUNT USD', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 10, 'GLName' => 'GL-335001', 'Description' => 'MB02 INTEREST PAYABLE ACCOUNT', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 2, 'GLName' => 'GL-335002', 'Description' => 'MB INTEREST PAYABLE ACCOUNT ZAR', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 10, 'GLName' => 'GL-336001', 'Description' => 'MICRO LOAN GENERAL LOAN LOSS PROVISION USD', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 10, 'GLName' => 'GL-336002', 'Description' => 'MICRO LOAN SPECIFIC LOAN LOSS PROVISION USD', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 10, 'GLName' => 'GL-336003', 'Description' => 'SME LOAN GENERAL LOAN LOSS PROVISION USD', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 10, 'GLName' => 'GL-336004', 'Description' => 'SME LOAN SPECIFIC LOAN LOSS PROVISION USD', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 10, 'GLName' => 'GL-336005', 'Description' => 'CORP SPECIFIC LOAN LOSS PROVISION USD', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 10, 'GLName' => 'GL-336006', 'Description' => 'STAFF LOAN SPECIFIC LOAN LOSS PROVISION USD', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 10, 'GLName' => 'GL-336007', 'Description' => 'SALARY BASED LOAN GENERAL LOAN LOSS PROVISION USD', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 10, 'GLName' => 'GL-336008', 'Description' => 'SALARY BASED LOAN SPECIFIC LOAN LOSS PROVISION USD', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 10, 'GLName' => 'GL-336009', 'Description' => 'SSB SPECIFIC LOAN LOSS PROVISION USD', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 10, 'GLName' => 'GL-336010', 'Description' => 'SSB GENERAL LOAN LOSS PROVISION USD', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 10, 'GLName' => 'GL-336011', 'Description' => 'PROVSBL SPECIFIC LOAN LOSS PROV', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 10, 'GLName' => 'GL-336012', 'Description' => 'FORMER STAFF SPECIFIC LOAN LOSS PROVISION', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 10, 'GLName' => 'GL-336013', 'Description' => 'CORP GENERAL LOAN LOSS PROVISION', 'GTType' => 'LIABILITY'],
            ['CurrencyID' => 10, 'GLName' => 'GL-336014', 'Description' => 'STAFF LOAN GENERAL LOAN LOSS PROVISION', 'GTType' => 'LIABILITY'],
        ];

        foreach ($accounts as $account) {
            DB::table('t_BudgetGLAccounts')->insert([
                'CurrencyID' => $account['CurrencyID'],
                'GLName' => $account['GLName'],
                'Description' => $account['Description'],
                'GTType' => $account['GTType'],
                'CreatedBy' => 1,
                'CreatedOn' => Carbon::now()->subDays(rand(1, 30)),
                'ModifiedBy' => 1,
                'ModifiedOn' => Carbon::now()->subDays(rand(0, 10)),
                'DeletedBy' => null,
                'DeletedOn' => null,
            ]);
        }
    }
}
