<?php

namespace App\Services\Finance;

use App\Models\Core\CodeDetail;
use App\Models\Finance\FinanceGLMapping; // mapping table model
use App\Models\Finance\FinanceJournalEntry;
use App\Models\Finance\FinanceJournalLines;
use App\Models\Finance\FinanceVoucher;
use App\Models\Finance\RecurrentJournal;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Str;
use Carbon\Carbon;
use Exception;
use Random\RandomException;

class TransactionService
{
    /** Target table (matches your migration) */
    protected string $txTable = 't_FinancialTransactions';

    /* ============================================================
     | Public API
     * ============================================================ */

    /**
     * Post transaction using mapping table (ModuleID + TransactionTypeID).
     * - Handles idempotency internally (no controller code)
     * - Validates payload and final lines
     * - Ensures DR == CR
     */
    public function postFromTypeMapping(array $payload, array $options = []): array
    {
        // 0) Validate minimal payload first (before queries)
        $this->validatePayloadForMapping($payload);

        // 1) Idempotency key (auto-generate if absent)
        $idempotencyKey = $payload['IdempotencyKey'] ?? (string) Str::uuid();

        // 2) Skip if already posted with same key
        $existing = DB::table($this->txTable)->where('IdempotencyKey', $idempotencyKey)->exists();
        if ($existing) {
            return ['status' => 'exists', 'message' => 'Transaction already posted for this idempotency key.'];
        }

        // 3) Resolve mapping
        $mapping = $this->resolveTypeMapping($payload['ModuleID'], $payload['TransactionTypeID']);

        // 4) Build base + lines from mapping
        $amount = (float)($payload['Amount'] ?? 0);
        $tax    = (float)($payload['TaxAmount'] ?? 0);
        $gross  = $amount + $tax;
        if ($gross <= 0) {
            throw new Exception('Amount must be greater than zero.');
        }

        $debitGL  = $payload['DebitGLAccountID']  ?? $mapping->DebitGLAccountID;
        $creditGL = $payload['CreditGLAccountID'] ?? $mapping->CreditGLAccountID;
        $taxGL    = $payload['TaxGLAccountID']    ?? null; // optional override (column not in mapping table)

        $base = [
            'TransactionDate'   => $payload['TransactionDate'] ?? Carbon::now()->toDateString(),
            'ThirdPartyID'      =>$payload['ThirdPartyID'] ?? null,
            'ReferenceNumber'   => $payload['ReferenceNumber'] ?? uniqid('REF-'),
            'TransactionType'   => (string)($payload['TransactionType'] ?? 'External'),
            'ModuleID'          => $payload['ModuleID'],
            'SourceTable'       => $payload['SourceTable'] ?? null,
            'BranchID'          => (int)($payload['BranchID'] ?? 1),
            'DepartmentID'      => $payload['DepartmentID'] ?? null,
            'CurrencyID'        => (int)($payload['CurrencyID'] ?? 1),
            'CurrencyCode'      => $payload['CurrencyCode'] ?? 'KES',
            'ExchangeRate'      => (float)($payload['ExchangeRate'] ?? 1),
            'Narration'         => $payload['Narration'] ?? null,
            'IsTaxable'         => (bool)($tax > 0),
            'SystemDescription' => $payload['SystemDescription'] ?? null,
            'IdempotencyKey'    => $idempotencyKey,
            'JournalRefNo'      => null,
        ];

        $lines = [
            $base + ['GLAccountID' => $debitGL,  'DRCR' => 'DR', 'Amount' => $amount],
            $base + ['GLAccountID' => $creditGL, 'DRCR' => 'CR', 'Amount' => $gross],
        ];

        if ($tax > 0) {
            if ($taxGL) {
                $lines[] = $base + [
                        'GLAccountID' => $taxGL,
                        'DRCR'        => 'DR',
                        'Amount'      => $tax,
                        'Narration'   => trim(($base['Narration'] ?? '').' (Tax)') ?: 'Tax',
                    ];
            } else {
                // No tax GL override: fold tax into debit
                $lines[0]['Amount'] += $tax;
            }
        }

        // 5) Stamp audit & batch
        $batch = $options['batch'] ?? $this->generateBatchNumber();
        $lines = $this->ensureAuditAndBatch($lines, $batch);

        // 6) Validate final lines against DB constraints and business rules
        $this->validateLines($lines);

        // 7) DR == CR
        $this->assertBalanced($lines);

        // 8) Create a JournalEntry and insert its line. Here I will automatically post them since they are externally generated by the system.
        $journalHeader = [
            'IsScheduled'            => $payload['IsScheduled']??false,
            'VoucherID'        => $payload['VoucherID'] ?? 0,
            'Date'            => $payload['TransactionDate'],
            'Description'     => 'Auto Journal'.$payload['TransactionType'].' '.$payload['ReferenceNumber'],
            'ReferenceNumber' => $payload['ReferenceNumber'],
            'BatchNumber'     => $payload['BatchNumber'] ?? null,
            'IdempotencyKey'  => 'JRN:'.$payload['ModuleID'].':'.$payload['TransactionTypeID'].':'.$payload['ReferenceNumber'],
            'CurrencyID'      => $payload['CurrencyID'],
        ];

        $journalResult =$this->createJournal($journalHeader, $lines);

        //Add The Journal Ref No
        if (!empty($journalResult['journal_ref'])) {
            foreach ($lines as &$line) {
                $line['JournalRefNo'] = $journalResult['journal_ref'];
            }
            unset($line); // break reference
        }
        // 9) Persist atomically
        return $this->persist($lines, ['batch' => $batch]);
    }

    /**
     * Reverse a previously posted BATCH (recommended),
     * flips DR/CR, keeps amounts positive, creates new batch.
     * @throws RandomException
     */
    public function reverseBatch(string $originalBatch, array $options = []): array
    {
        if (!$originalBatch) {
            throw new Exception('Original batch is required.');
        }

        $idKey = 'REV:'.$originalBatch;
        if (DB::table($this->txTable)->where('IdempotencyKey', $idKey)->exists()) {
            return ['status' => 'exists', 'message' => 'This batch was already reversed.'];
        }

        $original = DB::table($this->txTable)->where('BatchNumber', $originalBatch)->get();
        if ($original->isEmpty()) {
            throw new Exception("No transactions found for batch {$originalBatch}.");
        }

        $date    = $options['date'] ?? Carbon::now()->toDateString();
        $reason  = trim($options['reason'] ?? 'Reversal');
        $refPre  = $options['referencePrefix'] ?? 'REV-';
        $typeSuf = $options['typeSuffix'] ?? ' (Reversal)';

        $now = Carbon::now();
        $uid = Auth::id() ?? 0;

        $revLines = [];
        foreach ($original as $o) {
            $revLines[] = [
                'TransactionDate'     => $date,
                'ThirdPartyID'=> $o->ThirdPartyID ?? null,
                'ReferenceNumber'     => $refPre . ($o->ReferenceNumber ?? 'N/A'),
                'TransactionType'     => trim(($o->TransactionType ?? 'External') . $typeSuf),
                'TransactionTypeID'     => $o->TransactionTypeID,
                'ModuleID'            => (int)$o->ModuleID,
                'SourceTable'         => $o->SourceTable,
                'GLAccountID'         => (int)$o->GLAccountID,
                'BranchID'            => (int)$o->BranchID,
                'DepartmentID'        => $o->DepartmentID,
                'DRCR'                => $o->DRCR === 'DR' ? 'CR' : 'DR',
                'Amount'              => (float)$o->Amount,
                'CurrencyID'          => (int)$o->CurrencyID,
                'CurrencyCode'        => $o->CurrencyCode,
                'ExchangeRate'        => (float)$o->ExchangeRate,
                'Narration'           => trim(($o->Narration ? $o->Narration.' ' : '') . $reason . ' (REV)'),
                'BatchNumber'         => null, // set in ensureAuditAndBatch
                'IsTaxable'           => (bool)$o->IsTaxable,
                'IsReversal'          => 1,
                'ReversedTransactionID' => $o->Id, // link each line to the original row
                'SystemDescription'   => 'REV of '.$originalBatch,
                'IdempotencyKey'      => $idKey,
                'CreatedBy'           => $uid,
                'CreatedOn'           => $now,
                'ModifiedBy'          => $uid,
                'ModifiedOn'          => $now,
            ];
        }

        $revBatch = $this->generateReversalBatchNumber();
        $revLines = $this->ensureAuditAndBatch($revLines, $revBatch);

        // Validate + balance (should be fine if original was balanced)
        $this->validateLines($revLines);
        $this->assertBalanced($revLines);

        return $this->persist($revLines, ['batch' => $revBatch]);
    }

    /* ============================================================
     | Validation (Rules)
     * ============================================================ */

    /** Validate the incoming payload for mapping-driven post */
    protected function validatePayloadForMapping(array $payload): void
    {
        $rules = [
            'ModuleID'          => 'required',//|integer|exists:t_Modules,ModuleID', // adjust column if needed
            'ThirdPartyID'=> 'nullable|integer',
            'TransactionTypeID' => 'nullable|integer|exists:t_FinanceTransactionTypes,Id', // adjust
            'ReferenceNumber'   => 'required|string|max:100',
            'TransactionDate'   => 'nullable|date',
            'Amount'            => 'required|numeric|min:0.0000001',
            'TaxAmount'         => 'nullable|numeric|min:0',
            'BranchID'          => 'nullable|integer|exists:t_Branches,Id',
            'DepartmentID'      => 'nullable|integer|exists:t_Departments,Id',
            'CurrencyID'        => 'nullable|integer|exists:t_Currencies,Id',
            'CurrencyCode'      => 'nullable|string|max:10',
            'TransactionType'      => 'nullable|string|max:200',
            'ExchangeRate'      => 'nullable|numeric|min:0',
            'Narration'         => 'nullable|string|max:255',
            'SourceTable'       => 'nullable|string|max:100',
            'SystemDescription' => 'nullable|string|max:150',
            'IdempotencyKey'    => 'nullable|string|max:100',
            // optional overrides
            'DebitGLAccountID'  => 'nullable|integer|exists:t_FinanceGLAccounts,Id',
            'CreditGLAccountID' => 'nullable|integer|exists:t_FinanceGLAccounts,Id',
            'TaxGLAccountID'    => 'nullable|integer|exists:t_FinanceGLAccounts,Id',
        ];

        $v = Validator::make($payload, $rules);
        if ($v->fails()) {
            throw new Exception('Payload validation failed: ' . json_encode($v->errors()->toArray()));
        }
    }

    /** Validate the final lines that will be inserted */
    protected function validateLines(array $lines): void
    {
        // Rules are applied to an array of lines (dot-star syntax)
        $rules = [
            '*.TransactionDate'   => 'required|date',
            'ThirdPartyID'=> 'nullable|integer',
            '*.ReferenceNumber'   => 'required|string|max:100',
            '*.TransactionType'   => 'required|string|max:100',
            '*.TransactionTypeID'   => 'nullable|string|max:100',
            '*.ModuleID'          => 'nullable',//|integer', // FK not enforced here; already validated in payload
            '*.SourceTable'       => 'nullable|string|max:100',
            '*.GLAccountID'       => 'required|integer|exists:t_FinanceGLAccounts,Id',
            '*.BranchID'          => 'nullable|integer|exists:t_Branches,Id',
            '*.DepartmentID'      => 'nullable|integer|exists:t_Departments,Id',
            '*.DRCR'              => 'required|in:DR,CR',
            '*.Amount'            => 'required|numeric|min:0.0000001',
            '*.CurrencyID'        => 'nullable|integer|exists:t_Currencies,Id',
            '*.CurrencyCode'      => 'required|string|max:10',
            '*.ExchangeRate'      => 'required|numeric|min:0',
            '*.Narration'         => 'nullable|string|max:255',
            '*.BatchNumber'       => 'nullable|string|max:50',
            '*.IsTaxable'         => 'boolean',
            '*.IsReversal'        => 'nullable|boolean',
            '*.ReversedTransactionID' => 'nullable|integer|exists:'.$this->txTable.',Id',
            '*.SystemDescription' => 'nullable|string|max:150',
            '*.IdempotencyKey'    => 'required|string|max:100',
            '*.CreatedBy'         => 'required|integer|exists:t_Users,Id',
            '*.CreatedOn'         => 'required|date',
            '*.ModifiedBy'        => 'required|integer|exists:t_Users,Id',
            '*.ModifiedOn'        => 'required|date',
        ];

        $v = Validator::make($lines, $rules);
        if ($v->fails()) {
            throw new Exception('Line validation failed: ' . json_encode($v->errors()->toArray()));
        }
    }

    /** Ensure DR sum equals CR sum (within tiny tolerance) */
    protected function assertBalanced(array $lines, float $tol = 0.0001): void
    {
        $dr = 0.0; $cr = 0.0;
        foreach ($lines as $l) {
            $amt = (float)$l['Amount'];
            if ($l['DRCR'] === 'DR') $dr += $amt;
            if ($l['DRCR'] === 'CR') $cr += $amt;
        }
        if (abs($dr - $cr) > $tol) {
            throw new Exception("Unbalanced posting: DR={$dr} != CR={$cr}");
        }
    }

    /* ============================================================
     | Internals
     * ============================================================ */

    protected function resolveTypeMapping($moduleId, $transactionTypeId): FinanceGLMapping
    {
        $m = FinanceGLMapping::where('ModuleID', $moduleId)
            ->where('TransactionTypeID', $transactionTypeId)
            ->first();

        if (!$m) {
            throw new Exception("No active GL mapping for ModuleID {$moduleId}, TransactionTypeID {$transactionTypeId}.");
        }

        return $m;
    }

    /** Add audit fields and batch number */
    protected function ensureAuditAndBatch(array $lines, string $batch): array
    {
        $now = Carbon::now();
        $uid = Auth::id() ?? 0;

        return array_map(function ($l) use ($batch, $now, $uid) {
            $l['BatchNumber'] = $l['BatchNumber'] ?? $batch;
            $l['CreatedBy']   = $l['CreatedBy']   ?? $uid;
            $l['ModifiedBy']  = $l['ModifiedBy']  ?? $uid;
            $l['CreatedOn']   = $l['CreatedOn']   ?? $now;
            $l['ModifiedOn']  = $l['ModifiedOn']  ?? $now;
            return $l;
        }, $lines);
    }

    /** Persist lines atomically */

    protected function persist(array $lines, array $options): array
    {
        if (empty($lines)) {
            throw new \InvalidArgumentException('No lines to post.');
        }

        $batch = $options['batch'] ?? null;
        $ids   = [];

        DB::transaction(function () use ($lines, $batch, &$ids) {
            foreach ($lines as $line) {
                // Ensure Amount sign convention: DR -> negative, CR -> positive
                $isDebit = array_key_exists('IsDebit', $line)
                    ? (bool)$line['IsDebit']
                    : (($line['DRCR'] ?? null) === 'DR');
                $amt = abs((float)($line['Amount'] ?? 0));
                $storageLine = $line;
                $storageLine['Amount'] = $isDebit ? -$amt : $amt;

                // 1) insert one line, get its ID
                $trxId = DB::table($this->txTable)->insertGetId($storageLine);
                $ids[] = $trxId;

                // 2) update balances for that line (use abs amount internally)
                $this->updateBalanceForLine($trxId, $storageLine);
            }

            // 3) audit
            if (function_exists('activity')) {
                activity('Transaction Posting')
                    ->causedBy(Auth::id())
                    ->withProperties(['batch' => $batch, 'lines' => count($lines)])
                    ->log("Posted batch {$batch}");
            }
        });

        return [
            'status'          => 'success',
            'transactionIds'  => $ids,       // all inserted IDs
            'batchNumber'     => $batch,
            'count'           => count($lines),
        ];
    }

    /** Batch helpers
     * @throws RandomException
     */
    protected function generateBatchNumber(): string
    {
        return 'B' . Carbon::now()->format('YmdHis') . random_int(100, 999);
    }

    /**
     * @throws RandomException
     */
    protected function generateReversalBatchNumber(): string
    {
        return 'RB' . Carbon::now()->format('YmdHis') . random_int(100, 999);
    }

    /**
     * Create a Journal and its lines
     */
    public function createJournal(array $header, array $lines): array
    {
        // ---------- Idempotency ----------
        $jKey = $header['IdempotencyKey']
            ?? ('JRN:' . ($header['ReferenceNumber'] ?? 'REF') . ':' . ($header['BatchNumber'] ?? 'NB'));

        // If you store journals with an IdempotencyKey column, check that first.
        // If not, we’ll check by (Date, Description, BatchNumber) pattern as a fallback:
        $existing = FinanceJournalEntry::query()
            ->when(isset($header['IdempotencyKey']), fn($q) => $q->where('IdempotencyKey', $jKey))
            ->when(!isset($header['IdempotencyKey']), function ($q) use ($header) {
                $q->whereDate('Date', $header['Date'] ?? now()->toDateString())
                    ->where('Description', $header['Description'] ?? '')
                    ->when(!empty($header['BatchNumber']), fn($qq) => $qq->where('BatchNumber', $header['BatchNumber']));
            })
            ->first();

        if ($existing) {
            return ['status' => 'exists', 'journal_id' => $existing->Id, 'message' => 'Journal already exists (idempotent).'];
        }

        // ---------- Validate header ----------
        $hv = Validator::make($header, [
            'Date'            => 'required|date',
            'Description'     => 'nullable|string|max:255',
            'ReferenceNumber' => 'nullable|string|max:100',
            'BatchNumber'     => 'nullable|string|max:50',
            'IdempotencyKey'  => 'nullable|string|max:100',
        ]);
        if ($hv->fails()) {
            throw new \Exception('Journal header validation failed: ' . json_encode($hv->errors()->toArray()));
        }

        // ---------- Normalize + validate lines ----------
        if (empty($lines) || !is_array($lines[0] ?? null)) {
            throw new \Exception('Journal lines are required.');
        }

        // Normalize DR/CR -> IsDebit, Debit, Credit
        $norm = [];
        $totalDebit = 0.0; $totalCredit = 0.0;

        foreach ($lines as $i => $l) {
            $lv = Validator::make($l, [
                'GLAccountID'  => 'required|integer|exists:t_FinanceGLAccounts,Id',
                'BranchID'     => 'nullable|integer|exists:t_Branches,Id',
                'DepartmentID' => 'nullable|integer|exists:t_Departments,Id',
                'Amount'       => 'required|numeric|min:0.0000001',
                'DRCR'         => 'nullable|in:DR,CR',
                'IsDebit'      => 'nullable|boolean',
                'Narration'    => 'nullable|string|max:255',
            ]);
            if ($lv->fails()) {
                throw new \Exception("Journal line #".($i+1)." validation failed: " . json_encode($lv->errors()->toArray()));
            }

            $amount = (float)$l['Amount'];
            $isDebit = array_key_exists('IsDebit', $l)
                ? (bool)$l['IsDebit']
                : (($l['DRCR'] ?? null) === 'DR');

            $debit  = $isDebit ? $amount : 0.0;
            $credit = $isDebit ? 0.0 : $amount;

            $totalDebit  += $debit;
            $totalCredit += $credit;

            $norm[] = [
                'GLAccountID'  => (int)$l['GLAccountID'],
                'BranchID'     => $l['BranchID'] ?? null,
                'DepartmentID' => $l['DepartmentID'] ?? null,
                'IsDebit'      => $isDebit,
                'Amount' => $isDebit ? $amount * -1 : $amount,
                'Debit' => $debit * -1,
                'Credit'       => $credit,
                'Narration'    => $l['Narration'] ?? null,
            ];
        }

        if (round($totalDebit - $totalCredit, 6) !== 0.0) {
            throw new \Exception("Journal not balanced. DR={$totalDebit}, CR={$totalCredit}");
        }

        // ---------- Persist (single transaction) ----------
        return DB::transaction(function () use ($header, $norm, $totalDebit, $totalCredit, $jKey) {
            $uid = Auth::id() ?? 0;
            $now = Carbon::now();

            /** @var \App\Models\Finance\FinanceJournalEntry $journal */
            $journal = FinanceJournalEntry::create([
                'Date'           => $header['Date'],
                'Type'=> $header['IsScheduled']?'recurring':'normal',
                'SourceModule'   => $payload['ModuleID'] ?? '1100000', // Default to Finance module if not specified
                'Description'    => $header['Description'] ?? null,
                'SystemDescription'=>$header['Description'] ?? null,
                'Reference'      => $header['ReferenceNumber'] ?? null, // if your table has a Reference column
                'BatchNumber'    => $header['BatchNumber'] ?? null,     // add column if you want linkage
                'IdempotencyKey' => $jKey ?? null,                      // add column if you decide to store it
                'TotalDebit' => $totalDebit * -1 ?? null,                // optional summary cols if present
                'TotalCredit'    => $totalCredit ?? null,
                'CurrencyID'     => $header['CurrencyID'] ?? null,
                'ApprovalStatus'=>'posted',
                'ApprovalReason'=>'System Generated Approval.',
                'CreatedBy'      => 1,
                'ModifiedBy'     => 1,
                'CreatedOn'      => $now,
                'ModifiedOn'     => $now,
            ]);

            //Post rucurring Journal if so
            if($header['IsScheduled']){
                $voucher=FinanceVoucher::find($header['VoucherID']);
                RecurrentJournal::create([
                    'JournalEntryId'=> $journal->Id,
                    'StartDate'      => $voucher->StartDate,
                    'CuttOffDate'    =>  $voucher->StartDate,
                    'Frequency'      => CodeDetail::where('CodeID','JournalPaymentFrequency')
                                                ->where('Description',$voucher->Frequency)->value('Value'),
                    'ReferenceName'  => 'Voucher',
                    'Description'    => $voucher->Description,
                    'SystemDescription'=>'Auto Voucher Processing: '.$voucher->VoucherNo,
                    'CreatedBy'      =>1,
                    'ModifiedBy'     => 1,
                ]);
            }

            foreach ($norm as $ln) {
                FinanceJournalLines::create([
                    'JournalEntryId' => $journal->Id,
                    'GLAccountID'    => $ln['GLAccountID'],
                    'BranchID'       => $ln['BranchID'],
                    'DepartmentID'   => $ln['DepartmentID'],
                    'IsDebit'        => $ln['IsDebit'],
                    'Amount' => $ln['IsDebit'] ? $ln['Amount'] * -1 : $ln['Amount'],
                    'Debit' => $ln['Debit'] * -1,
                    'Credit'         => $ln['Credit'],
                    'Narration'      => $ln['Narration'],
                    'SystemDescription'      => $ln['Narration'],
                    'CreatedBy'      => 1,
                    'ModifiedBy'     => 1,
                ]);
            }

            if (function_exists('activity')) {
                activity('Journal Create')
                    ->performedOn($journal)
                    ->causedBy($uid)
                    ->withProperties(['lines' => count($norm)])
                    ->log('Created Journal '.$journal->Id);
            }

            return [
                'status'       => 'success',
                'journal_id'   => $journal->Id,
                'journal_ref'  =>$journal->RefNo,
                'lines_count'  => count($norm),
            ];
        });
    }

    protected function updateBalanceForLine(int $trxId, array $trx): void
    {
        $glAccountId = (int)$trx['GLAccountID'];
        $branchId    = $trx['BranchID'] ?? null;
        $amount = abs((float)$trx['Amount']);
        $drcr        = strtoupper($trx['DRCR'] ?? 'DR');     // DR or CR
        $rate        = (float)($trx['ExchangeRate'] ?? 1);
        $currencyId  = $trx['CurrencyID'] ?? null;

        // Sign: DR = -, CR = + (always start from absolute amount)
        $signed       = $drcr === 'DR' ? -$amount : $amount;

        // Base/ledger currency deltas (t_FinanceGLBranch stores all three)
        $localDelta   = $signed * $rate;   // base/ledger currency delta
        $foreignDelta = $currencyId ? $signed : 0;

        // Format to avoid float noise in SQL
        $fmt = fn($n) => number_format((float)$n, 5, '.', '');

        $uid = $trx['ModifiedBy'] ?? $trx['CreatedBy'] ?? (Auth::id() ?? 0);
        $now = now();

        // Grab GL meta (code + type). Prefer character "A/L/E/I/X" if available.
        $glMeta = DB::table('t_FinanceGLAccounts')
            ->select('GLCode', 'GLAccountTypeID')
            ->where('Id', $glAccountId)
            ->first();

        $glCode        = $trx['GLCode']        ?? ($glMeta->GLCode ?? '');
        $glAccountType = $trx['GLAccountTypeID'] ?? ($glMeta->GLAccountType ?? ($glMeta->GLAccountTypeID ?? null));

        // Does the (GLAccountID, BranchID) row exist?
        $exists = DB::table('t_FinanceGLBranch')
            ->where('GLAccountID', $glAccountId)
            ->when(is_null($branchId), fn($q) => $q->whereNull('BranchID'),
                fn($q) => $q->where('BranchID', $branchId))
            ->exists();

        if ($exists) {
            // UPDATE path → increment balances
            DB::table('t_FinanceGLBranch')
                ->when(true, function ($q) use ($glAccountId, $branchId) {
                    $q->where('GLAccountID', $glAccountId);
                    return is_null($branchId) ? $q->whereNull('BranchID') : $q->where('BranchID', $branchId);
                })
                ->update([
                    'LastTransactionId' => $trxId,
                    // increment with DB::raw – use base/ledger delta for Balance/LocalBalance
                    'Balance'           => DB::raw('Balance + '      . $fmt($localDelta)),
                    'LocalBalance'      => DB::raw('LocalBalance + ' . $fmt($localDelta)),
                    'ForeignBalance'    => DB::raw('ForeignBalance + ' . $fmt($foreignDelta)),
                    'ModifiedOn'        => $now,
                    'ModifiedBy'        => $uid,
                ]);

        } else {
            // INSERT path → set starting balances (no arithmetic here)
            DB::table('t_FinanceGLBranch')->insert([
                'GLAccountID'       => $glAccountId,
                'BranchID'          => $branchId,
                'GLCode'            => $glCode,
                'GLAccountType'     => (string)$glAccountType,
                'LastTransactionId' => $trxId,
                'IsActive'          => 1,
                'BankID'            => $trx['BankID'] ?? null,

                // starting balances (base/ledger = localDelta)
                'Balance'           => $fmt($localDelta),
                'LocalBalance'      => $fmt($localDelta),
                'ForeignBalance'    => $fmt($foreignDelta),

                // audit — set BOTH created & modified to satisfy NOT NULL constraints
                'CreatedOn'         => $now,
                'CreatedBy'         => $trx['CreatedBy'] ?? $uid,
                'ModifiedOn'        => $now,
                'ModifiedBy'        => $uid,
            ]);
        }
    }

}
