@extends('layouts.app')
@section('title', 'reportmanagement')
@section('content')
<div class="container mt-4">
  <h4 class="mb-3">Generate Insurance Report</h4>

  <form>
    <div class="mb-3">
      <label for="reportType" class="form-label">Select Report Type</label>
      <select class="form-select" id="reportType" required>
        <option value="">-- Choose --</option>
        <option value="active_policies">All Active Policies</option>
        <option value="policy_per_asset">Policy per Asset</option>
        <option value="claims_summary">Claims Summary (by status/type)</option>
        <option value="upcoming_premiums">Upcoming Premiums</option>
        <option value="expired_policies">Expired Policies</option>
      </select>
    </div>

    <div class="mb-3">
      <label for="startDate" class="form-label">Start Date (Optional)</label>
      <input type="date" class="form-control" id="startDate">
    </div>

    <div class="mb-3">
      <label for="endDate" class="form-label">End Date (Optional)</label>
      <input type="date" class="form-control" id="endDate">
    </div>

    <div class="mb-3">
      <label for="generatedBy" class="form-label">Generated By</label>
      <input type="text" class="form-control" id="generatedBy" placeholder="Enter your name" required>
    </div>

    <div class="mb-3">
      <label for="notes" class="form-label">Additional Notes</label>
      <textarea class="form-control" id="notes" rows="3" placeholder="Optional comments..."></textarea>
    </div>

    <button type="submit" class="btn btn-primary">Generate Report</button>
  </form>
</div>
@endsection